/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class AplikasiInventarisBarang extends javax.swing.JFrame {

  
    public AplikasiInventarisBarang() {
        initComponents();
        setLocationRelativeTo(this); // membuat tampilan berada di posisi tengah saat di jalankan
        btnedit.setEnabled(false); // mematikan tombol edit
        
       
        
        
    }
     private void clear() {
        //method bersihkan secara otomatis
        tfMerek.setText(null); // mengset semua text field dan cbbx ke null/kosong 
        tfkdbarang.setText(null);
        tfsatuan.setText(null);
        tfstok.setText(null);
        cbbx.setSelectedItem("");
        tfkdbarang.requestFocus(true);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbbx = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfMerek = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfkdbarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfstok = new javax.swing.JTextField();
        tfsatuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnexport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(792, 585));

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(430, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("KODE BARANG");

        cbbx.setBackground(new java.awt.Color(153, 153, 153));
        cbbx.setForeground(new java.awt.Color(255, 255, 255));
        cbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOBIL", "MOTOR", "HANDPHONE", "TV", "KULKAS", "AC", "KIPAS ANGIN", "MESIN CUCI", " " }));
        cbbx.setBorder(null);
        cbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("MEREK");

        tfMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMerekActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("KATEGORI");

        tfkdbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkdbarangActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("STOCK");

        tfstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfstokKeyTyped(evt);
            }
        });

        tfsatuan.setEditable(false);
        tfsatuan.setFocusable(false);
        tfsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsatuanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("SATUAN");

        btnTambah.setBackground(new java.awt.Color(0, 153, 153));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnbersihkan.setBackground(new java.awt.Color(0, 153, 153));
        btnbersihkan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnbersihkan.setForeground(new java.awt.Color(255, 255, 255));
        btnbersihkan.setText("Bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfsatuan, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(tfstok)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(tfMerek)
                    .addComponent(tfkdbarang)
                    .addComponent(cbbx, 0, 274, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfkdbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfstok, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 590);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(430, 500));

        tbl.setBackground(new java.awt.Color(246, 246, 246));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KODE BARANG", "MEREK", "KATEGORI", "STOCK", "SATUAN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.setFocusable(false);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        btnedit.setBackground(new java.awt.Color(242, 242, 216));
        btnedit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(0, 0, 0));
        btnedit.setText("Edit");
        btnedit.setEnabled(false);
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 51, 51));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("Hapus");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(242, 242, 216));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(0, 0, 0));
        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnImport.setBackground(new java.awt.Color(242, 242, 216));
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnexport.setBackground(new java.awt.Color(242, 242, 216));
        btnexport.setText("export");
        btnexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addComponent(btnImport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnexport)
                .addGap(22, 22, 22))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnexport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(342, 0, 460, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbxActionPerformed
           int pilih = cbbx.getSelectedIndex(); // jika combobok kategori di pilih
           switch (pilih) {
            case 0: 
                tfsatuan.setText("Buah"); //case 0 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 1:
                tfsatuan.setText("Buah"); //case 1 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 2:
                tfsatuan.setText("Buah"); //case 2 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 3:
                tfsatuan.setText("Buah"); //case 3 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 4:
                tfsatuan.setText("Buah"); //case 4 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 5:
                tfsatuan.setText("Buah"); //case 5 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 6:
                tfsatuan.setText("Buah"); //case 6 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
                case 7:
                tfsatuan.setText("Buah"); //case 7 maka textfield pada satuan akan terisi secara ototmatis ke buah
                
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_cbbxActionPerformed

    private void tfMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMerekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMerekActionPerformed

    private void tfkdbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkdbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkdbarangActionPerformed

    private void tfsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsatuanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
 int line = tbl.getSelectedRow();  // variabel line dia ambil dari pilihan baris
            
            tfkdbarang.setText(tbl.getValueAt(line, 0).toString()); //text field kode barang di set ke isi value pada colom 0 dan baris ke string
            tfMerek.setText(tbl.getValueAt(line, 1).toString());
            cbbx.setSelectedItem(tbl.getValueAt(line,2).toString());
            tfstok.setText(tbl.getValueAt(line, 3).toString());
            tfsatuan.setText(tbl.getValueAt(line, 3).toString());
            
            btnTambah.setEnabled(false);
            btnedit.setEnabled(false); // mengemabilan button edit keadaan mati
            btnSimpan.setEnabled(true); // button simpan akan hidup
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
int respon =JOptionPane.showConfirmDialog(null, "hapus Isi tabel yang di pilih ?" ,"delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if (respon==JOptionPane.YES_OPTION) {
             DefaultTableModel model = (DefaultTableModel) tbl.getModel(); //default tabelmode ke model
             int[] baris = tbl.getSelectedRows();       //pilih baris untuk di hapus
         for(int i=0;i<baris.length;i++){
              model.removeRow(baris[i]-i); // 
             }
             btnedit.setEnabled(false); // mengembalikan button edit ke keadaan mati
             btnhapus.setEnabled(false); // mengembalikan button hapus ke keadaan mati

        }
 
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
             DefaultTableModel model=(DefaultTableModel) tbl.getModel();  //default tabel model ke model
        
                    
            //jika button tambah di klik maka
            if ( tfkdbarang.getText().trim().equals("") ||
               tfMerek.getText().trim().equals("") ||
               cbbx.getSelectedItem().equals("") ||
              tfstok.getText().trim().equals("") ||
              tfsatuan.getText().trim().equals("") ) {
                JOptionPane.showMessageDialog(null, "Harus di isi","Peringatan",JOptionPane.WARNING_MESSAGE); //Pesan kesalalhan
               }else{//tetapi jika txtfield dan cbbx ada isi value nya maka akan di tambah kan ke tabel melalu array object
            model.addRow(new Object[]{tfkdbarang.getText(),tfMerek.getText(),cbbx.getSelectedItem(),tfstok.getText(),tfsatuan.getText()});
            JOptionPane.showMessageDialog(null, "Data berhasil di tambahkan","Suksess",JOptionPane.INFORMATION_MESSAGE);
            }
            clear(); //dan akan menjalankan method kosong
            tbl.setModel(model);
            
        } catch (Exception e) {
        }
       
          
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
      clear();//memanggil method clear
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void tfstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfstokKeyTyped
  
        char c= evt.getKeyChar();
        if(! ((Character.isDigit(c)) || // jika textStock di ketik  SELAIN HURUF ANGKA 1-9  maka akan muncul peringan 
            ( c== KeyEvent.VK_BACK_SPACE)
            || (c== KeyEvent.VK_DELETE)
        ))
        {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "masukan anga 1-9");
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_tfstokKeyTyped

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
                                          //jika form tabel di klik maka btn edit dan btn hapus akan hidup
        btnedit.setEnabled(true);
       btnhapus.setEnabled(true);
       
       
    }//GEN-LAST:event_tblMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         try {
             DefaultTableModel model=(DefaultTableModel) tbl.getModel(); //default tabelmode ke model
               int line =tbl.getSelectedRow();// pilih baris tabel
            
            if ( (line>= 0) ) {
            model.setValueAt(tfkdbarang.getText(), line, 0); //model mengset isi value  textfield dan cbbx ke baris dan kolom pada tabel secara urutan
            model.setValueAt(tfMerek.getText(), line, 1);
            model.setValueAt(cbbx.getSelectedItem(), line, 2);
            model.setValueAt(tfstok.getText(), line, 3); 
            model.setValueAt(tfsatuan.getText(), line, 3); 
             JOptionPane.showMessageDialog(null, "DATA BERHASIL DI Simpan", "Confirm",JOptionPane.INFORMATION_MESSAGE);
            }else{
               JOptionPane.showMessageDialog(null, "ERORR ?", "Confirm",JOptionPane.INFORMATION_MESSAGE);
               
                }
        clear(); // membersihan txt field 

            btnedit.setEnabled(true); // mengembalikan button edit,simpan,dan tambah  ke keadaan mati
            btnSimpan.setEnabled(false);
            btnTambah.setEnabled(true);
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportActionPerformed
     String filePath = "C:\\Users\\Administrator\\Documents\\NetBeansProjects\\TitisSukmono-2110010021-UTS\\export\\data_tabel.txt"; 
        File file = new File(filePath);
        
        try {
            FileWriter fw = new FileWriter(file);
             BufferedWriter bw = new BufferedWriter(fw);
            
            for(int i = 0; i < tbl.getRowCount(); i++){//rows
                for(int j = 0; j < tbl.getColumnCount(); j++){//columns
                    bw.write(tbl.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
               
            }
             JOptionPane.showMessageDialog(null, "Berhasil DI eksport");
            
            
            bw.close();
            fw.close();
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnexportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
      String filePath = "C:\\Users\\Administrator\\Documents\\NetBeansProjects\\TitisSukmono-2110010021-UTS\\import\\data_tabel.txt";
      //variabe flePath di ambil dari alamat dokumen yang menuju ke data_tabel.txt
        File file = new File(filePath);
        
        try {
            FileReader fr = new FileReader(file); 
            BufferedReader br = new BufferedReader(fr);
            
            DefaultTableModel model = (DefaultTableModel)tbl.getModel();
            Object[] lines = br.lines().toArray();
            
            for(int i = 0; i < lines.length; i++){
                String[] row = lines[i].toString().split(" ");
                model.addRow(row);
                
            }
             JOptionPane.showMessageDialog(null, "Berhasil mengImport data"); //pesan ketika berhasil meng import
            
            
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiInventarisBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiInventarisBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnexport;
    private javax.swing.JButton btnhapus;
    private javax.swing.JComboBox<String> cbbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tfMerek;
    private javax.swing.JTextField tfkdbarang;
    private javax.swing.JTextField tfsatuan;
    private javax.swing.JTextField tfstok;
    // End of variables declaration//GEN-END:variables

    private static class tbl_import_and_export_to_text_file {

       
    }

   
}
